import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { overviewChart, effectSummary, effectLabel, EFFECT_DOMAIN } from '../src/pages/overview-chart.ts';
import { count, percent } from '../src/format.ts';
import type { OverviewRow } from '../src/data.generated.ts';
const row: OverviewRow = JSON.parse(readFileSync(new URL('../public/data/overview.json', import.meta.url), 'utf8')).rows[0];
assert.equal(row.randomized_participants, row.intervention_participants + row.control_participants);
assert.equal(row.randomized_participants, row.evaluation_participants + row.missing_primary_outcome);
assert.equal(row.villages, row.intervention_villages + row.control_villages);
assert.equal(count(row.randomized_participants), '4,533');
assert.equal(percent(row.evaluation_participants / row.randomized_participants), '99.4%');
assert.equal(percent(row.missing_primary_outcome / row.randomized_participants), '0.6%');
assert.deepEqual(EFFECT_DOMAIN, [-3, 1]);
assert.equal(effectLabel(row.treatment_effect_estimate), '−1.880');
assert(effectSummary(row).includes('-2.564 to -1.196 pp'));
const option = overviewChart(row) as any;
assert.equal(option.xAxis.min, -3); assert.equal(option.xAxis.max, 1); assert.equal(option.xAxis.interval, 1);
assert.equal(option.animation, false);
assert.equal(option.series[0].markLine.data[0].xAxis, 0);
assert.deepEqual(option.series[0].data[0], [row.treatment_effect_ci_lower, row.treatment_effect_estimate, row.treatment_effect_ci_upper]);
const api = { coord: ([x, y]: number[]) => [(x + 3) * 150, y * 100], getWidth: () => 600 };
const group = option.series[0].renderItem({}, api);
assert.equal(group.children[0].shape.x1, (row.treatment_effect_ci_lower + 3) * 150);
assert.equal(group.children[0].shape.x2, (row.treatment_effect_ci_upper + 3) * 150);
assert.equal(group.children[3].shape.cx, (row.treatment_effect_estimate + 3) * 150);
assert.deepEqual(group.children.slice(4).map((item: any) => item.style.text), ['−2.564', '−1.880', '−1.196']);
const narrow = option.series[0].renderItem({}, { ...api, getWidth: () => 320 });
assert.equal(narrow.children.length, 5);
assert.equal(narrow.children[4].style.text, '−1.880');
console.log('PASS: Overview source counts/shares, exact fixed-domain CI geometry, zero/caps/estimate, display precision and readable narrow label treatment.');
