// Generated by scripts/export_web_data.py. Do not hand-edit.
export interface PublicDataset<Name extends string, Row> { readonly schema_name: Name; readonly schema_version: "1.0.0"; readonly rows: readonly Row[]; }

export interface OverviewRow {
  readonly summary_id: "SMARTER_PRIMARY";
  readonly randomized_participants: number;
  readonly evaluation_participants: number;
  readonly missing_primary_outcome: number;
  readonly villages: number;
  readonly intervention_participants: number;
  readonly control_participants: number;
  readonly intervention_villages: number;
  readonly control_villages: number;
  readonly primary_outcome: "Predicted 10-year ASCVD risk";
  readonly outcome_unit: "percentage points";
  readonly treatment_effect_estimate: number;
  readonly treatment_effect_ci_lower: number;
  readonly treatment_effect_ci_upper: number;
  readonly effect_favorable_direction: "lower";
  readonly benefit_sign_convention: "positive benefit equals a reduction in predicted ASCVD risk";
  readonly analysis_population: "randomized participants with observed primary follow-up outcome";
  readonly reproduction_status: "REPRODUCED";
  readonly final_policy_conclusion: "NO SINGLE ROBUST POLICY WINNER ESTABLISHED";
}

export interface VillagesRow {
  readonly village_id: string;
  readonly n_randomized: number;
  readonly baseline_risk: number;
  readonly grf_predicted_benefit: number;
  readonly simple_predicted_benefit: number;
  readonly grf_candidate_rank: number;
  readonly simple_candidate_rank: number;
  readonly baseline_risk_candidate_rank: number;
}

export interface ValidationRow {
  readonly validation_id: "calibration:grf" | "calibration:simple" | "evidence:grf_hte_validation" | "evidence:grf_vs_baseline_risk" | "evidence:incremental_grf_vs_simple" | "participant_spearman:grf_vs_baseline_risk" | "participant_spearman:grf_vs_simple" | "participant_spearman:simple_vs_baseline_risk" | "rate:within_fold:AUTOC:baseline_risk" | "rate:within_fold:AUTOC:grf" | "rate:within_fold:AUTOC:random" | "rate:within_fold:AUTOC:simple" | "village_spearman:mean_benefit_grf_oov_vs_mean_benefit_simple_oov" | "village_spearman:mean_benefit_grf_oov_vs_mean_risk0" | "village_spearman:mean_benefit_simple_oov_vs_mean_risk0";
  readonly metric: "AUTOC" | "calibration_slope" | "evidence_classification" | "priority_spearman" | "village_signal_spearman";
  readonly model_or_comparison: "baseline_risk" | "grf" | "grf_hte_validation" | "grf_vs_baseline_risk" | "grf_vs_simple" | "incremental_grf_vs_simple" | "mean_benefit_grf_oov_vs_mean_benefit_simple_oov" | "mean_benefit_grf_oov_vs_mean_risk0" | "mean_benefit_simple_oov_vs_mean_risk0" | "random" | "simple" | "simple_vs_baseline_risk";
  readonly normalization: "fold_adjusted" | "predeclared_rule" | "raw_participant_scores" | "village_aggregate" | "within_fold";
  readonly estimate: number | null;
  readonly ci_lower: number | null;
  readonly ci_upper: number | null;
  readonly classification: "NOT DEMONSTRATED" | "SUPPORTED" | "positive alignment" | null;
  readonly unit: "classification" | "correlation" | "slope" | "validation score";
  readonly scientific_category: "descriptive" | "evidence_classification" | "heuristic_validation" | "predictive_causal_hte_validation" | "sanity_check";
}

export interface SubgroupsRow {
  readonly subgroup_effect_id: "subgroup_00" | "subgroup_01" | "subgroup_02" | "subgroup_03" | "subgroup_04" | "subgroup_05" | "subgroup_06" | "subgroup_07" | "subgroup_08" | "subgroup_09" | "subgroup_10" | "subgroup_11" | "subgroup_12";
  readonly moderator: "Overall" | "age" | "baseline_risk" | "education" | "income" | "occupation" | "sex";
  readonly moderator_label: "Age" | "Annual household income" | "Baseline 10-year ASCVD risk" | "Education" | "Occupation" | "Overall" | "Sex";
  readonly subgroup: "<10,000 yuan" | "<16%" | "<60 years" | ">=10,000 yuan" | ">=16%" | ">=60 years" | "Agricultural worker" | "Below high school" | "High school or above" | "Men" | "Non-agricultural worker" | "Overall" | "Women";
  readonly analysis_n: number;
  readonly treatment_effect: number;
  readonly ci_lower: number;
  readonly ci_upper: number;
  readonly reconstruction_status: "CANONICAL PHASE-4 RESULT" | "PARTIALLY RECONSTRUCTABLE" | "VERIFIED";
  readonly unit: "percentage points of predicted 10-year ASCVD risk";
  readonly favorable_direction: "lower";
  readonly scientific_category: "causal_subgroup_estimate";
}

export interface RolloutRow {
  readonly policy: "baseline_risk" | "grf" | "simple";
  readonly capacity_villages: number;
  readonly n_selected_randomized: number;
  readonly point_population_rollout_value: number;
  readonly point_random_expected_value: number;
  readonly point_gain_vs_random: number;
  readonly population_value_ci_lower: number;
  readonly population_value_ci_upper: number;
  readonly gain_ci_lower: number;
  readonly gain_ci_upper: number;
  readonly interval_type: "pointwise_95_percentile_bootstrap";
  readonly bootstrap_replicates: number;
  readonly is_fixed_anchor: boolean;
}

export interface AnchorsRow {
  readonly policy: "baseline_risk" | "grf" | "simple";
  readonly capacity_villages: number;
  readonly point_population_rollout_value: number;
  readonly population_value_ci_lower: number;
  readonly population_value_ci_upper: number;
  readonly point_random_expected_value: number;
  readonly point_gain_vs_random: number;
  readonly gain_ci_lower: number;
  readonly gain_ci_upper: number;
  readonly interval_type: "pointwise_95_percentile_bootstrap";
  readonly bootstrap_replicates: number;
  readonly policy_vs_random_classification: "INCONCLUSIVE" | "RECONCILIATION ENDPOINT";
  readonly capacity_advantage_label: "NO CLEAR CAPACITY-SPECIFIC ADVANTAGE" | "RECONCILIATION ENDPOINT";
  readonly selected_villages: number;
  readonly n_selected_randomized: number;
  readonly randomized_coverage: number;
  readonly n_selected_evaluation: number;
  readonly evaluation_coverage: number;
  readonly anchor_role: "fixed_inference" | "reconciliation";
}

export interface OverlapRow {
  readonly capacity_villages: number;
  readonly comparison: "grf_vs_baseline_risk" | "grf_vs_simple" | "simple_vs_baseline_risk";
  readonly policy_left: "grf" | "simple";
  readonly policy_right: "baseline_risk" | "simple";
  readonly shared_villages: number;
  readonly jaccard_overlap: number;
  readonly scientific_category: "descriptive";
}

export interface RobustnessRow {
  readonly policy: "baseline_risk" | "grf" | "simple";
  readonly capacity_villages: number;
  readonly phase11a_point_gain_vs_random: number;
  readonly phase11a_gain_ci_lower: number;
  readonly phase11a_gain_ci_upper: number;
  readonly phase11a_gain_classification: "INCONCLUSIVE";
  readonly phase11a_capacity_advantage_label: "NO CLEAR CAPACITY-SPECIFIC ADVANTAGE";
  readonly raw_ranking_stability: "SENSITIVE";
  readonly equal_village_consistency: "CONSISTENT";
  readonly single_village_influence: "ROBUST TO SINGLE-VILLAGE DELETION" | "SENSITIVE TO SINGLE-VILLAGE DELETION";
  readonly scientific_category: "causal_policy_evaluation_and_sensitivity";
}

export interface CoverageRow {
  readonly policy: "baseline_risk" | "grf" | "simple";
  readonly capacity_villages: number;
  readonly capacity_role: "endpoint_reconciliation" | "fixed_descriptive_anchor";
  readonly dimension: "age" | "education" | "income" | "occupation" | "sex";
  readonly dimension_label: "Age" | "Annual household income" | "Education" | "Occupation" | "Sex";
  readonly category: "<10,000 yuan" | "<60 years" | ">=10,000 yuan" | ">=60 years" | "Agricultural worker" | "Below high school" | "High school or above" | "Men" | "Non-agricultural worker" | "Women";
  readonly n_subgroup_total: number;
  readonly n_subgroup_covered: number;
  readonly subgroup_coverage: number;
  readonly n_overall_covered: number;
  readonly overall_randomized_coverage: number;
  readonly coverage_gap: number;
  readonly analysis_note: "Coverage comparisons are descriptive and are not fairness-optimization criteria.";
  readonly scientific_category: "descriptive";
}

export interface PoliciesRow {
  readonly policy: "baseline_risk" | "grf" | "simple";
  readonly policy_label: "Baseline risk" | "GRF" | "Simple HTE";
  readonly scientific_category: "heuristic" | "predictive_causal_hte";
}

export interface CapacitiesRow {
  readonly capacity_villages: number;
  readonly is_fixed_anchor: boolean;
  readonly capacity_role: "curve_only" | "fixed_inference" | "reconciliation";
}

export interface WebDatasets {
  readonly overview: PublicDataset<"overview", OverviewRow>;
  readonly villages: PublicDataset<"villages", VillagesRow>;
  readonly validation: PublicDataset<"validation", ValidationRow>;
  readonly subgroups: PublicDataset<"subgroups", SubgroupsRow>;
  readonly rollout: PublicDataset<"rollout", RolloutRow>;
  readonly anchors: PublicDataset<"anchors", AnchorsRow>;
  readonly overlap: PublicDataset<"overlap", OverlapRow>;
  readonly robustness: PublicDataset<"robustness", RobustnessRow>;
  readonly coverage: PublicDataset<"coverage", CoverageRow>;
  readonly policies: PublicDataset<"policies", PoliciesRow>;
  readonly capacities: PublicDataset<"capacities", CapacitiesRow>;
}
